### PR TITLE
Zone 16 invalid entities

### LINKED ISSUE #189: Invalid Cast Exceptions on startup (since forever, cleanup)
Low priority, worth investigating, doesn't seem to affect anything after startup.

```
[15:13:33] ERR ZoneUnitReader: CreateUnit error. eid = 1328
[15:13:33] ERR 
Exception Found:
Type: System.InvalidCastException
Message: Unable to cast object of type 'Perpetuum.EntityFramework.Entity' to type 'Perpetuum.Items.Item'.
Source: Perpetuum
Stacktrace:    at Perpetuum.Items.ItemHelper.CreateItem(Int32 definition, EntityIDGenerator idGenerator)
   at Perpetuum.Zones.ZoneEntityRepositories.ZoneUnitReader.CreateUnit(IDataRecord record)
[15:13:33] ERR ZoneUnitReader: CreateUnit error. eid = 1329
[15:13:33] ERR 
Exception Found:
Type: System.InvalidCastException
Message: Unable to cast object of type 'Perpetuum.EntityFramework.Entity' to type 'Perpetuum.Items.Item'.
Source: Perpetuum
Stacktrace:    at Perpetuum.Items.ItemHelper.CreateItem(Int32 definition, EntityIDGenerator idGenerator)
   at Perpetuum.Zones.ZoneEntityRepositories.ZoneUnitReader.CreateUnit(IDataRecord record)
[15:13:33] ERR ZoneUnitReader: CreateUnit error. eid = 1339
[15:13:33] ERR 
Exception Found:
Type: System.InvalidCastException
Message: Unable to cast object of type 'Perpetuum.EntityFramework.Entity' to type 'Perpetuum.Items.Item'.
Source: Perpetuum
Stacktrace:    at Perpetuum.Items.ItemHelper.CreateItem(Int32 definition, EntityIDGenerator idGenerator)
   at Perpetuum.Zones.ZoneEntityRepositories.ZoneUnitReader.CreateUnit(IDataRecord record)
```

### PR DESCRIPTION
**Pull request by Doc-Saintly**
Man, this is the 3rd+ time I'm writing this just to delete a few entities... This is to clean up zone entities that are throwing exceptions on startup.

Closes: https://github.com/OpenPerpetuum/PerpetuumServer/issues/189

### CODE REVIEW

File: Staging_Dev/Zone_16_invalid_entities__2020_09_16.sql [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+GO
+
+-----------------------------------------------
+-- Some zone entities left over in Zone 16
+-- throwing exceptions during server startup
+--
+-- Date: 2020/09/16
+-----------------------------------------------
+
+DELETE FROM zoneentities WHERE id IN (1528, 1529, 1539)
```
Comment (MikeJeffers) [inline Staging_Dev/Zone_16_invalid_entities__2020_09_16.sql]: I know its a bit much, but can you look these up by name (or some unique varchar col)?
It is a baseline assumption, even if these records are from 'vanilla', that table id's are not to be relied on for stable migrations.

Comment (MikeJeffers) [reply Staging_Dev/Zone_16_invalid_entities__2020_09_16.sql]: Also a convention to add `GO` to the end of any singular patch file as it closes scope.  This assists with avoiding conflicts, namespace issues, etc. when rollups are done.

**Review by MikeJeffers — CHANGES_REQUESTED** [review]
Can you merge/rebase your branch off latest `development`?  The Patch 18 rollup is showing as a diff.

**Review by MikeJeffers — APPROVED** [review]
